import { Router } from "express";
import authRoutes from "./auth/interfaces/http/auth.routes";
import productRoutes from "./product/interfaces/http/product.routes";
import categoryRoutes from "./category/interfaces/http/category.routes";
import cartRoutes from "./cart/interfaces/http/cart.routes";
import orderRoutes from "./order/interfaces/http/order.routes";
import userRoutes from "./user/interfaces/http/user.routes";
import accountRoutes from "./account/interfaces/http/account.routes";
import roleRoutes from "./role/interfaces/http/role.routes";
import settingRoutes from "./setting/interfaces/http/setting.routes";
import dashboardRoutes from "./dashboard/interfaces/http/dashboard.routes";
import couponRoutes from "./coupon/interfaces/http/coupon.routes";
import couponPublicRoutes from "./coupon/interfaces/http/coupon-public.routes";
import { requireAdmin } from "../shared/middleware/admin-auth.middleware";
const domainRouter = Router();
// Public routes (no authentication required)
domainRouter.use(authRoutes);
domainRouter.use(productRoutes);
domainRouter.use(categoryRoutes);
domainRouter.use(cartRoutes);
domainRouter.use(orderRoutes);
domainRouter.use(userRoutes);
domainRouter.use("/coupons", couponPublicRoutes);
domainRouter.use(requireAdmin);
domainRouter.use("/coupons", couponRoutes);
domainRouter.use(accountRoutes);
domainRouter.use(roleRoutes);
domainRouter.use(settingRoutes);
domainRouter.use(dashboardRoutes);

export default domainRouter;
